spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/sales
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect



  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 1076498484313-2f32tufs6nmbchvb10ubai30qer6ij7h.apps.googleusercontent.com
          clientSecret: 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
          scope:
           - email
           - profile